plugins {
	id "application"
	id "com.gradleup.shadow" version "8.3.6"
}

dependencies {
	implementation project(":core")
	implementation project(":core-config")
	implementation(libs.gson)
	implementation(libs.guava)
	implementation(libs.bundles.netty.all)
	implementation(libs.slf4j)
	implementation(libs.velocity.nightconfig)
	runtimeOnly(libs.logback)
}

application {
	mainClass = "net.lax1dude.eaglercraft.backend.server.standalone.StandaloneMain"
}

tasks.named("shadowJar", com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
	archiveFileName = "EaglerXServer-Standalone.jar"
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}